version: '3'

services:
  database:
    image: postgres:12-alpine
    container_name: database
    env_file:
      - .env.postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - 5432

  mediasabak:
    build: .
    container_name: mediasabak
    command: bash -c "gunicorn -b :8000 main.wsgi"
    env_file:
      - .env.django
    volumes:
      - .:/app
    ports:
      - 127.0.0.1:8000:8000
    depends_on:
      - database

volumes:
  pgdata:
