version: '3'
services:
  db:
    image: postgres:13
    container_name: db
    volumes:
      - ./postgres_data/:/var/lib/postgresql/
    env_file:
      - .env
    environment:
      - POSTGRES_DB=factorioprints
      - TZ=Asia/Bishkek

  web:
    build: .
    container_name: web
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=factorioprints.settings
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=factorioprints
      - TZ=Asia/Bishkek
    depends_on:
      - nginx
      - db
    volumes:
    - ./static:/app/static
    - ./media:/app/media
    - ./media/images:/app/media/images

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
      - ./static:/app/static
      - ./media:/app/media
      - ./media/article_images:/app/media/article_images
      - ./media/blurred_article_images:/app/media/blurred_article_images
      - ./media/qr:/app/media/qr
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
