# Generated by Django 3.0 on 2022-02-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, verbose_name='Prints Unique Key')),
                ('author', models.CharField(max_length=150, verbose_name='Автор')),
                ('details', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Подробности')),
                ('blueprint', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Строка чертежа')),
                ('image', models.ImageField(upload_to='images', verbose_name='Изображение чертежа')),
                ('created_at', models.DateField(db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateField(db_index=True, verbose_name='Обновлено в')),
                ('favorites', models.CharField(max_length=10, verbose_name='Избранное')),
            ],
            options={
                'verbose_name': 'Чертеж',
                'verbose_name_plural': 'Чертежи',
                'ordering': ['-created_at'],
            },
        ),
    ]
