# Generated by Django 3.0 on 2022-02-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printparser', '0002_auto_20220205_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prints',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Изображение чертежа'),
        ),
    ]
